[package]
name = "nvapi-sys"
version = "0.1.3"
authors = ["arcnmx"]

description = "NVIDIA NVAPI FFI bindings"
keywords = ["nvidia", "nvapi", "gtx"]

documentation = "http://arcnmx.github.io/nvapi-rs/nvapi_sys"
repository = "https://github.com/arcnmx/nvapi-rs"
readme = "../README.md"
license = "MIT"

[target.'cfg(windows)'.dependencies]
winapi = { version = "^0.3.4", features = ["libloaderapi", "unknwnbase"] }

[dependencies]
bitflags = "^1.0.1"
serde = { version = "^1.0.0", features = ["derive"], optional = true }

[features]
serde_types = ["serde"]
default = ["serde_types"]
